// Copyright (c) 2005-2009 Jaroslav Gresula
//
// Distributed under the MIT license (See accompanying file
// LICENSE.txt or copy at http://jagpdf.org/LICENSE.txt)
//


#ifndef __MSGCODES_H_GENERATED__
#define __MSGCODES_H_GENERATED__

#if defined(_MSC_VER) && (_MSC_VER>=1020)
#   pragma once
#endif


// this is a file generated by genexc.py on 12/27/07 21:28:24

#include <core/errlib/msgrecord.h>


namespace jag
{

const UInt WRN_TT_EMBEDDING_NOT_ALLOWED_w = 0;
const UInt WRN_TYPE1_EMBEDDING_NOT_SUPPORTED_w = 1;
const UInt WRN_WARNING_WHILE_PROCESSING_PNG_FORMAT_w = 2;
const UInt WRN_UNKOWN_PNG_RESOLUTION_i = 3;
const UInt WRN_PNG_MORE_THEN_ONE_COLOR_KEY_MASK = 4;
const UInt WRN_ALPHA_IGNORED = 5;
const UInt WRN_IMAGE_MASK_IGNORED = 6;
const UInt WRN_COLOR_KEY_MASK_IGNORED = 7;
const UInt WRN_ALTERNATE_FOR_PRINTING_IGNORED = 8;
const UInt WRN_IMAGE_RENDERING_INTENT_OUT_OF_RANGE = 9;
const UInt WRN_PAINTING_NOTHING = 10;
const UInt WRN_GR_STATE_MODIFIED_WITHIN_PATH_CONSTRUCTION = 11;
const UInt WRN_FREETYPE_FINALIZATION_FAILED_i = 12;
const UInt WRN_EMPTY_DOCUMENT = 13;
const UInt WRN_NO_FONT_SENT = 14;
const UInt WRN_GLYPH_INDEX_OUT_OF_RANGE_uw = 15;
const UInt WRN_CODEPOINT_NOT_FOUND_IN_FONT_uw = 16;
const UInt WRN_FALLBACK_FONT_USED_INSTEAD_w = 17;
const UInt WRN_FORCED_EMBEDDING_w = 18;
const UInt WRN_MATTE_DIMENSIONS_MISMATCH = 19;
const UInt INF_TEST_MESSAGE = 20;
const UInt INF_TEST_MESSAGE_w = 21;

const UInt TOTAL_NUMBER_OF_MESSAGES = 22;
extern const MessageRecord msg_records[TOTAL_NUMBER_OF_MESSAGES];

} //namespace jag

#endif //__MSGCODES_H_GENERATED__

