// Copyright (c) 2005-2009 Jaroslav Gresula
//
// Distributed under the MIT license (See accompanying file
// LICENSE.txt or copy at http://jagpdf.org/LICENSE.txt)
//


#include "precompiled.h"
#include "encdifferences.h"
#include <core/errlib/errlib.h>

// generated by encdiff2.py

namespace jag {
namespace pdf {

namespace {

// difference strings against WinAnsiEncoding


Char const* const str_ENC_CP_1250 =
"129 /.notdef\n"
"131 /.notdef\n"
"136 /.notdef\n"
"140 /Sacute /Tcaron\n"
"143 /Zacute /.notdef\n"
"152 /.notdef\n"
"156 /sacute /tcaron\n"
"159 /zacute\n"
"161 /caron /breve /Lslash\n"
"165 /Aogonek\n"
"170 /Scedilla\n"
"175 /Zdot\n"
"178 /ogonek /lslash\n"
"185 /aogonek /scedilla\n"
"188 /Lcaron /hungarumlaut /lcaron /zdot /Racute\n"
"195 /Abreve\n"
"197 /Lacute /Cacute\n"
"200 /Ccaron\n"
"202 /Eogonek\n"
"204 /Ecaron\n"
"207 /Dcaron /Dcroat /Nacute /Ncaron\n"
"213 /Odblacute\n"
"216 /Rcaron /Uring\n"
"219 /Uhungarumlaut\n"
"222 /Tcedilla\n"
"224 /racute\n"
"227 /abreve\n"
"229 /lacute /cacute\n"
"232 /ccaron\n"
"234 /eogonek\n"
"236 /ecaron\n"
"239 /dcaron /dcroat /nacute /ncaron\n"
"245 /ohungarumlaut\n"
"248 /rcaron /uring\n"
"251 /udblacute\n"
"254 /tcedilla /dotaccent";


Char const* const str_ENC_MAC_ROMAN =
"128 /Adieresis /Aring /Ccedilla /Eacute /Ntilde /Odieresis /Udieresis /aacute\n"
"/agrave /acircumflex /adieresis /atilde /aring /ccedilla /eacute /egrave\n"
"/ecircumflex /edieresis /iacute /igrave /icircumflex /idieresis /ntilde\n"
"/oacute /ograve /ocircumflex /odieresis /otilde /uacute /ugrave /ucircumflex\n"
"/udieresis /dagger /degree\n"
"164 /section /bullet /paragraph /germandbls /registered\n"
"170 /trademark /acute /dieresis /notequal /AE /Oslash /infinity\n"
"178 /lessequal /greaterequal /yen\n"
"182 /partialdiff /summation /product /pi /integral /ordfeminine /ordmasculine\n"
"/Omegagreek /ae /oslash /questiondown /exclamdown /logicalnot /radical /florin\n"
"/approxequal /Delta /guillemotleft /guillemotright /ellipsis /nbspace /Agrave\n"
"/Atilde /Otilde /OE /oe /endash /emdash /quotedblleft /quotedblright /quoteleft\n"
"/quoteright /divide /lozenge /ydieresis /Ydieresis /fraction /euro /guilsinglleft\n"
"/guilsinglright /fi /fl /daggerdbl /middot /quotesinglbase /quotedblbase\n"
"/perthousand /Acircumflex /Ecircumflex /Aacute /Edieresis /Egrave /Iacute\n"
"/Icircumflex /Idieresis /Igrave /Oacute /Ocircumflex /apple /Ograve /Uacute\n"
"/Ucircumflex /Ugrave /dotlessi /circumflex /ilde /macron /breve /dotaccent\n"
"/ring /cedilla /hungarumlaut /ogonek /caron";


Char const* const str_ENC_CP_1251 =
"128 /Djecyrillic /Gjecyrillic\n"
"131 /gjecyrillic\n"
"136 /euro\n"
"138 /afii10058\n"
"140 /afii10059 /Kjecyrillic /afii10060 /afii10145 /djecyrillic\n"
"152 /.notdef\n"
"154 /afii10106\n"
"156 /afii10107 /kjecyrillic /tshecyrillic /afii10193\n"
"161 /Ushortcyrillic /afii10110 /Jecyrillic\n"
"165 /afii10050\n"
"168 /afii10023\n"
"170 /afii10053\n"
"175 /afii10056\n"
"178 /afii10055 /icyrillic /gheupturncyrillic\n"
"184 /iocyrillic /afii61352 /afii10101\n"
"188 /afii10105 /afii10054 /afii10102 /afii10104 /Acyrillic /afii10018 /Vecyrillic\n"
"/Gecyrillic /afii10021 /afii10022 /Zhecyrillic /afii10025 /afii10026 /afii10027\n"
"/afii10028 /afii10029 /afii10030 /afii10031 /afii10032 /afii10033 /Ercyrillic\n"
"/afii10035 /afii10036 /afii10037 /afii10038 /afii10039 /Tsecyrillic /afii10041\n"
"/Shacyrillic /afii10043 /afii10044 /Yericyrillic /Softsigncyrillic /afii10047\n"
"/afii10048 /afii10049 /afii10065 /afii10066 /afii10067 /afii10068 /afii10069\n"
"/iecyrillic /afii10072 /zecyrillic /iicyrillic /iishortcyrillic /kacyrillic\n"
"/afii10077 /emcyrillic /encyrillic /ocyrillic /pecyrillic /ercyrillic /escyrillic\n"
"/tecyrillic /ucyrillic /efcyrillic /afii10087 /afii10088 /checyrillic /afii10090\n"
"/shchacyrillic /hardsigncyrillic /yericyrillic /softsigncyrillic /ereversedcyrillic\n"
"/iucyrillic /iacyrillic";


Char const* const str_ENC_CP_1253 =
"129 /.notdef\n"
"136 /.notdef\n"
"138 /.notdef\n"
"140 /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"152 /.notdef\n"
"154 /.notdef\n"
"156 /.notdef /.notdef /.notdef /.notdef\n"
"161 /dialytikatonos /Alphatonos\n"
"175 /afii00208\n"
"180 /tonos\n"
"184 /Epsilontonos /Etatonos /Iotatonos\n"
"188 /Omicrontonos\n"
"190 /Upsilontonos /Omegatonos /iotadieresistonos /Alpha /Beta /Gamma /Deltagreek\n"
"/Epsilon /Zeta /Eta /Theta /Iota /Kappa /Lambda /Mu /Nu /Xi /Omicron /Pi\n"
"/Rho /.notdef /Sigma /Tau /Upsilon /Phi /Chi /Psi /Omegagreek /Iotadieresis\n"
"/Upsilondieresis /alphatonos /epsilontonos /etatonos /iotatonos /upsilondieresistonos\n"
"/alpha /beta /gamma /delta /epsilon /zeta /eta /theta /iota /kappa /lambda\n"
"/mugreek /nu /xi /omicron /pi /rho /sigmafinal /sigma /tau /upsilon /phi\n"
"/chi /psi /omega /iotadieresis /upsilondieresis /omicrontonos /upsilontonos\n"
"/omegatonos /.notdef";


Char const* const str_ENC_CP_1254 =
"129 /.notdef\n"
"141 /.notdef /.notdef /.notdef /.notdef\n"
"157 /.notdef /.notdef\n"
"208 /Gbreve\n"
"221 /Idotaccent /Scedilla\n"
"240 /gbreve\n"
"253 /dotlessi /scedilla";


Char const* const str_ENC_CP_1255 =
"129 /.notdef\n"
"138 /.notdef\n"
"140 /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"154 /.notdef\n"
"156 /.notdef /.notdef /.notdef /.notdef\n"
"164 /newsheqelsign\n"
"170 /multiply\n"
"186 /divide\n"
"192 /shevanarrowhebrew /hatafsegolquarterhebrew /hatafpatahnarrowhebrew /hatafqamats1b\n"
"/hiriqwidehebrew /tserehebrew /segolhebrew /patahwidehebrew /qamatsqatanwidehebrew\n"
"/holam /.notdef /qubuts31 /dagesh /siluqlefthebrew /afii57645 /rafehebrew\n"
"/afii57842 /shindothebrew /sindothebrew /sofpasuqhebrew /afii57716 /afii57717\n"
"/afii57718 /gereshhebrew /gershayimhebrew /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /afii57664 /bet /afii57666 /afii57667 /he /vav\n"
"/zayinhebrew /het /tethebrew /yodhebrew /finalkaf /kaf /lamed /finalmemhebrew\n"
"/afii57678 /finalnun /afii57680 /afii57681 /afii57682 /afii57683 /afii57684\n"
"/afii57685 /afii57686 /afii57687 /afii57688 /afii57689 /afii57690 /.notdef\n"
"/.notdef /afii299 /afii300 /.notdef";


Char const* const str_ENC_CP_1256 =
"129 /afii57506\n"
"138 /afii57511\n"
"141 /afii57507 /afii57508 /afii57512 /afii57509\n"
"152 /.notdef\n"
"154 /afii57513\n"
"157 /zerowidthnonjoiner /afii301 /afii57514\n"
"161 /afii57388\n"
"170 /.notdef\n"
"186 /afii57403\n"
"191 /afii57407 /haaltonearabic /afii57409 /afii57410 /alefhamzaabovearabic\n"
"/afii57412 /afii57413 /yehhamzaabovearabic /afii57415 /afii57416 /afii57417\n"
"/afii57418 /afii57419 /afii57420 /afii57421 /khaharabic /afii57423 /afii57424\n"
"/afii57425 /zainarabic /afii57427 /sheenarabic /afii57429 /afii57430\n"
"216 /afii57431 /afii57432 /afii57433 /afii57434 /tatweelarabic /feharabic\n"
"/qafarabic /afii57443\n"
"225 /afii57444\n"
"227 /meemarabic /noonarabic /heharabic /wawarabic\n"
"236 /afii57449 /yeharabic\n"
"240 /fathatanarabic /dammatanarabic /kasratanarabic /afii57454\n"
"245 /dammaarabic /afii57456\n"
"248 /afii57457\n"
"250 /sukunarabic\n"
"253 /afii299 /afii300 /afii57519";


Char const* const str_ENC_CP_1257 =
"129 /.notdef\n"
"131 /.notdef\n"
"136 /.notdef\n"
"138 /.notdef\n"
"140 /.notdef /dieresis /caron /cedilla /.notdef\n"
"152 /.notdef\n"
"154 /.notdef\n"
"156 /.notdef /macron /ogonek /.notdef\n"
"161 /.notdef\n"
"165 /.notdef\n"
"168 /Oslash\n"
"170 /Rcommaaccent\n"
"175 /AE\n"
"184 /oslash\n"
"186 /rcedilla\n"
"191 /ae /Aogonek /Iogonek /Amacron /Cacute\n"
"198 /Eogonek /Emacron /Ccaron\n"
"202 /Zacute /Edot /Gcedilla /Kcommaaccent /Imacron /Lcedilla /Scaron /Nacute\n"
"/Ncommaaccent\n"
"212 /Omacron\n"
"216 /Uogonek /Lslash /Sacute /Umacron\n"
"221 /Zdot /Zcaron\n"
"224 /aogonek /iogonek /amacron /cacute\n"
"230 /eogonek /emacron /ccaron\n"
"234 /zacute /edotaccent /gcommaaccent /kcedilla /imacron /lcommaaccent /scaron\n"
"/nacute /ncedilla\n"
"244 /omacron\n"
"248 /uogonek /lslash /sacute /umacron\n"
"253 /zdot /zcaron /dotaccent";


Char const* const str_ENC_CP_1258 =
"129 /.notdef\n"
"138 /.notdef\n"
"141 /.notdef /.notdef /.notdef /.notdef\n"
"154 /.notdef\n"
"157 /.notdef /.notdef\n"
"195 /Abreve\n"
"204 /gravecomb\n"
"208 /Dcroat\n"
"210 /hookabovecomb\n"
"213 /Ohorn\n"
"221 /Uhorn /tildecomb\n"
"227 /abreve\n"
"236 /acutecmb\n"
"240 /dcroat\n"
"242 /dotbelowcomb\n"
"245 /ohorn\n"
"253 /uhorn /dong";


Char const* const str_ENC_ISO_8859_1 =
"128 /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef";


Char const* const str_ENC_ISO_8859_2 =
"128 /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"161 /Aogonek /breve /Lslash\n"
"165 /Lcaron /Sacute\n"
"169 /Scaron /Scedilla /Tcaron /Zacute\n"
"174 /Zcaron /Zdot\n"
"177 /aogonek /ogonek /lslash\n"
"181 /lcaron /sacute /caron\n"
"185 /scaron /scedilla /tcaron /zacute /hungarumlaut /zcaron /zdot /Racute\n"
"195 /Abreve\n"
"197 /Lacute /Cacute\n"
"200 /Ccaron\n"
"202 /Eogonek\n"
"204 /Ecaron\n"
"207 /Dcaron /Dcroat /Nacute /Ncaron\n"
"213 /Odblacute\n"
"216 /Rcaron /Uring\n"
"219 /Uhungarumlaut\n"
"222 /Tcedilla\n"
"224 /racute\n"
"227 /abreve\n"
"229 /lacute /cacute\n"
"232 /ccaron\n"
"234 /eogonek\n"
"236 /ecaron\n"
"239 /dcaron /dcroat /nacute /ncaron\n"
"245 /ohungarumlaut\n"
"248 /rcaron /uring\n"
"251 /udblacute\n"
"254 /tcedilla /dotaccent";


Char const* const str_ENC_ISO_8859_3 =
"128 /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"161 /Hbar /breve\n"
"165 /.notdef /Hcircumflex\n"
"169 /Idotaccent /Scedilla /Gbreve /Jcircumflex\n"
"174 /.notdef /Zdot\n"
"177 /hbar\n"
"182 /hcircumflex\n"
"185 /dotlessi /scedilla /gbreve /jcircumflex\n"
"190 /.notdef /zdot\n"
"195 /.notdef\n"
"197 /Cdot /Ccircumflex\n"
"208 /.notdef\n"
"213 /Gdot\n"
"216 /Gcircumflex\n"
"221 /Ubreve /Scircumflex\n"
"227 /.notdef\n"
"229 /cdot /ccircumflex\n"
"240 /.notdef\n"
"245 /gdotaccent\n"
"248 /gcircumflex\n"
"253 /ubreve /scircumflex /dotaccent";


Char const* const str_ENC_ISO_8859_4 =
"128 /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"161 /Aogonek /kgreenlandic /Rcommaaccent\n"
"165 /Itilde /Lcedilla\n"
"169 /Scaron /Emacron /Gcedilla /Tbar\n"
"174 /Zcaron\n"
"177 /aogonek /ogonek /rcedilla\n"
"181 /itilde /lcommaaccent /caron\n"
"185 /scaron /emacron /gcommaaccent /tbar /Eng /zcaron /eng /Amacron\n"
"199 /Iogonek /Ccaron\n"
"202 /Eogonek\n"
"204 /Edot\n"
"207 /Imacron /Dcroat /Ncommaaccent /Omacron /Kcommaaccent\n"
"217 /Uogonek\n"
"221 /Utilde /Umacron\n"
"224 /amacron\n"
"231 /iogonek /ccaron\n"
"234 /eogonek\n"
"236 /edotaccent\n"
"239 /imacron /dcroat /ncedilla /omacron /kcedilla\n"
"249 /uogonek\n"
"253 /utilde /umacron /dotaccent";


Char const* const str_ENC_ISO_8859_5 =
"128 /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"161 /afii10023 /Djecyrillic /Gjecyrillic /afii10053 /afii10054 /afii10055\n"
"/afii10056 /Jecyrillic /afii10058 /afii10059 /afii10060 /Kjecyrillic\n"
"174 /Ushortcyrillic /afii10145 /Acyrillic /afii10018 /Vecyrillic /Gecyrillic\n"
"/afii10021 /afii10022 /Zhecyrillic /afii10025 /afii10026 /afii10027 /afii10028\n"
"/afii10029 /afii10030 /afii10031 /afii10032 /afii10033 /Ercyrillic /afii10035\n"
"/afii10036 /afii10037 /afii10038 /afii10039 /Tsecyrillic /afii10041 /Shacyrillic\n"
"/afii10043 /afii10044 /Yericyrillic /Softsigncyrillic /afii10047 /afii10048\n"
"/afii10049 /afii10065 /afii10066 /afii10067 /afii10068 /afii10069 /iecyrillic\n"
"/afii10072 /zecyrillic /iicyrillic /iishortcyrillic /kacyrillic /afii10077\n"
"/emcyrillic /encyrillic /ocyrillic /pecyrillic /ercyrillic /escyrillic /tecyrillic\n"
"/ucyrillic /efcyrillic /afii10087 /afii10088 /checyrillic /afii10090 /shchacyrillic\n"
"/hardsigncyrillic /yericyrillic /softsigncyrillic /ereversedcyrillic /iucyrillic\n"
"/iacyrillic /afii61352 /iocyrillic /djecyrillic /gjecyrillic /afii10101\n"
"/afii10102 /icyrillic /afii10104 /afii10105 /afii10106 /afii10107 /tshecyrillic\n"
"/kjecyrillic /section /afii10110 /afii10193";


Char const* const str_ENC_ISO_8859_6 =
"128 /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"161 /.notdef /.notdef /.notdef\n"
"165 /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /afii57388\n"
"174 /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /afii57403 /.notdef /.notdef\n"
"/.notdef /afii57407 /.notdef /afii57409 /afii57410 /alefhamzaabovearabic\n"
"/afii57412 /afii57413 /yehhamzaabovearabic /afii57415 /afii57416 /afii57417\n"
"/afii57418 /afii57419 /afii57420 /afii57421 /khaharabic /afii57423 /afii57424\n"
"/afii57425 /zainarabic /afii57427 /sheenarabic /afii57429 /afii57430 /afii57431\n"
"/afii57432 /afii57433 /afii57434 /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/tatweelarabic /feharabic /qafarabic /afii57443 /afii57444 /meemarabic /noonarabic\n"
"/heharabic /wawarabic /afii57449 /yeharabic /fathatanarabic /dammatanarabic\n"
"/kasratanarabic /afii57454 /dammaarabic /afii57456 /afii57457 /sukunarabic\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef";


Char const* const str_ENC_ISO_8859_7 =
"128 /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"161 /quoteleft /quoteright\n"
"164 /euro /.notdef\n"
"170 /ypogegrammeni\n"
"174 /.notdef /afii00208\n"
"180 /tonos /dialytikatonos /Alphatonos\n"
"184 /Epsilontonos /Etatonos /Iotatonos\n"
"188 /Omicrontonos\n"
"190 /Upsilontonos /Omegatonos /iotadieresistonos /Alpha /Beta /Gamma /Deltagreek\n"
"/Epsilon /Zeta /Eta /Theta /Iota /Kappa /Lambda /Mu /Nu /Xi /Omicron /Pi\n"
"/Rho /.notdef /Sigma /Tau /Upsilon /Phi /Chi /Psi /Omegagreek /Iotadieresis\n"
"/Upsilondieresis /alphatonos /epsilontonos /etatonos /iotatonos /upsilondieresistonos\n"
"/alpha /beta /gamma /delta /epsilon /zeta /eta /theta /iota /kappa /lambda\n"
"/mugreek /nu /xi /omicron /pi /rho /sigmafinal /sigma /tau /upsilon /phi\n"
"/chi /psi /omega /iotadieresis /upsilondieresis /omicrontonos /upsilontonos\n"
"/omegatonos /.notdef";


Char const* const str_ENC_ISO_8859_8 =
"128 /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"161 /.notdef\n"
"170 /multiply\n"
"186 /divide\n"
"191 /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/dbllowline /afii57664 /bet /afii57666 /afii57667 /he /vav /zayinhebrew\n"
"/het /tethebrew /yodhebrew /finalkaf /kaf /lamed /finalmemhebrew /afii57678\n"
"/finalnun /afii57680 /afii57681 /afii57682 /afii57683 /afii57684 /afii57685\n"
"/afii57686 /afii57687 /afii57688 /afii57689 /afii57690 /.notdef /.notdef\n"
"/afii299 /afii300 /.notdef";


Char const* const str_ENC_ISO_8859_9 =
"128 /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"208 /Gbreve\n"
"221 /Idotaccent /Scedilla\n"
"240 /gbreve\n"
"253 /dotlessi /scedilla";


Char const* const str_ENC_ISO_8859_10 =
"128 /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"161 /Aogonek /Emacron /Gcedilla /Imacron /Itilde /Kcommaaccent\n"
"168 /Lcedilla /Dcroat /Scaron /Tbar /Zcaron\n"
"174 /Umacron /Eng\n"
"177 /aogonek /emacron /gcommaaccent /imacron /itilde /kcedilla\n"
"184 /lcommaaccent /dcroat /scaron /tbar /zcaron /afii00208 /umacron /eng\n"
"/Amacron\n"
"199 /Iogonek /Ccaron\n"
"202 /Eogonek\n"
"204 /Edot\n"
"209 /Ncommaaccent /Omacron\n"
"215 /Utilde\n"
"217 /Uogonek\n"
"224 /amacron\n"
"231 /iogonek /ccaron\n"
"234 /eogonek\n"
"236 /edotaccent\n"
"241 /ncedilla /omacron\n"
"247 /utilde\n"
"249 /uogonek\n"
"255 /kgreenlandic";


Char const* const str_ENC_ISO_8859_11 =
"128 /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"161 /kokaithai /khokhaithai /khokhuatthai /khokhwaithai /khokhonthai /khorakhangthai\n"
"/ngonguthai /chochanthai /chochingthai /chochangthai /sosothai /chochoethai\n"
"/yoyingthai /dochadathai /topatakthai /thothanthai /thonangmonthothai /thophuthaothai\n"
"/nonenthai /dodekthai /totaothai /thothungthai /thothahanthai /thothongthai\n"
"/nonuthai /bobaimaithai /poplathai /phophungthai /fofathai /phophanthai\n"
"/fofanthai /phosamphaothai /momathai /yoyakthai /roruathai /ruthai /lolingthai\n"
"/luthai /wowaenthai /sosalathai /sorusithai /sosuathai /hohipthai /lochulathai\n"
"/oangthai /honokhukthai /paiyannoithai /saraathai /maihanakatthai /saraaathai\n"
"/saraamthai /saraithai /saraiithai /sarauethai /saraueethai /sarauthai /sarauuthai\n"
"/phinthuthai /.notdef /.notdef /.notdef /.notdef /bahtthai /saraethai /saraaethai\n"
"/saraothai /saraaimaimuanthai /saraaimaimalaithai /lakkhangyaothai /maiyamokthai\n"
"/maitaikhuthai /maiekthai /maithothai /maitrithai /maichattawathai /thanthakhatthai\n"
"/nikhahitthai /yamakkanthai /fongmanthai /zerothai /onethai /twothai /threethai\n"
"/fourthai /fivethai /sixthai /seventhai /eightthai /ninethai /angkhankhuthai\n"
"/khomutthai /.notdef /.notdef /.notdef /.notdef";


Char const* const str_ENC_ISO_8859_13 =
"128 /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"161 /quotedblright\n"
"165 /quotedblbase\n"
"168 /Oslash\n"
"170 /Rcommaaccent\n"
"175 /AE\n"
"180 /quotedblleft\n"
"184 /oslash\n"
"186 /rcedilla\n"
"191 /ae /Aogonek /Iogonek /Amacron /Cacute\n"
"198 /Eogonek /Emacron /Ccaron\n"
"202 /Zacute /Edot /Gcedilla /Kcommaaccent /Imacron /Lcedilla /Scaron /Nacute\n"
"/Ncommaaccent\n"
"212 /Omacron\n"
"216 /Uogonek /Lslash /Sacute /Umacron\n"
"221 /Zdot /Zcaron\n"
"224 /aogonek /iogonek /amacron /cacute\n"
"230 /eogonek /emacron /ccaron\n"
"234 /zacute /edotaccent /gcommaaccent /kcedilla /imacron /lcommaaccent /scaron\n"
"/nacute /ncedilla\n"
"244 /omacron\n"
"248 /uogonek /lslash /sacute /umacron\n"
"253 /zdot /zcaron /quoteright";


Char const* const str_ENC_ISO_8859_14 =
"128 /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"161 /Bdotaccent /bdotaccent\n"
"164 /Cdot /cdot /Ddotaccent\n"
"168 /Wgrave\n"
"170 /Wacute /ddotaccent /Ygrave\n"
"175 /Ydieresis /Fdotaccent /fdotaccent /Gdot /gdotaccent /Mdotaccent /mdotaccent\n"
"183 /Pdotaccent /wgrave /pdotaccent /wacute /Sdotaccent /ygrave /Wdieresis\n"
"/wdieresis /sdotaccent\n"
"208 /Wcircumflex\n"
"215 /Tdotaccent\n"
"222 /Ycircumflex\n"
"240 /wcircumflex\n"
"247 /tdotaccent\n"
"254 /ycircumflex";


Char const* const str_ENC_ISO_8859_15 =
"128 /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"164 /euro\n"
"166 /Scaron\n"
"168 /scaron\n"
"180 /Zcaron\n"
"184 /zcaron\n"
"188 /OE /oe /Ydieresis";


Char const* const str_ENC_ISO_8859_16 =
"128 /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef\n"
"161 /Aogonek /aogonek /Lslash /euro /quotedblbase /Scaron\n"
"168 /scaron\n"
"170 /Scommaaccent\n"
"172 /Zacute\n"
"174 /zacute /Zdot\n"
"178 /Ccaron /lslash /Zcaron /quotedblright\n"
"184 /zcaron /ccaron /scommaaccent\n"
"188 /OE /oe /Ydieresis /zdot\n"
"195 /Abreve\n"
"197 /Cacute\n"
"208 /Dcroat /Nacute\n"
"213 /Odblacute\n"
"215 /Sacute /Uhungarumlaut\n"
"221 /Eogonek /.notdef\n"
"227 /abreve\n"
"229 /cacute\n"
"240 /dcroat /nacute\n"
"245 /ohungarumlaut\n"
"247 /sacute /udblacute\n"
"253 /eogonek /.notdef";


} //anonymous namespace


Char const* enc_differences(EnumCharacterEncoding enc)
{
    switch(enc)
    {
    case ENC_CP_1250       : return str_ENC_CP_1250;
    case ENC_MAC_ROMAN     : return str_ENC_MAC_ROMAN;
    case ENC_CP_1251       : return str_ENC_CP_1251;
    case ENC_CP_1253       : return str_ENC_CP_1253;
    case ENC_CP_1254       : return str_ENC_CP_1254;
    case ENC_CP_1255       : return str_ENC_CP_1255;
    case ENC_CP_1256       : return str_ENC_CP_1256;
    case ENC_CP_1257       : return str_ENC_CP_1257;
    case ENC_CP_1258       : return str_ENC_CP_1258;
    case ENC_ISO_8859_1    : return str_ENC_ISO_8859_1;
    case ENC_ISO_8859_2    : return str_ENC_ISO_8859_2;
    case ENC_ISO_8859_3    : return str_ENC_ISO_8859_3;
    case ENC_ISO_8859_4    : return str_ENC_ISO_8859_4;
    case ENC_ISO_8859_5    : return str_ENC_ISO_8859_5;
    case ENC_ISO_8859_6    : return str_ENC_ISO_8859_6;
    case ENC_ISO_8859_7    : return str_ENC_ISO_8859_7;
    case ENC_ISO_8859_8    : return str_ENC_ISO_8859_8;
    case ENC_ISO_8859_9    : return str_ENC_ISO_8859_9;
    case ENC_ISO_8859_10   : return str_ENC_ISO_8859_10;
    case ENC_ISO_8859_11   : return str_ENC_ISO_8859_11;
    case ENC_ISO_8859_13   : return str_ENC_ISO_8859_13;
    case ENC_ISO_8859_14   : return str_ENC_ISO_8859_14;
    case ENC_ISO_8859_15   : return str_ENC_ISO_8859_15;
    case ENC_ISO_8859_16   : return str_ENC_ISO_8859_16;
    default:
        JAG_INTERNAL_ERROR;
    }
}

bool supports_differences(EnumCharacterEncoding enc)
{
    switch(enc)
    {
    case ENC_CP_1250:
    case ENC_MAC_ROMAN:
    case ENC_CP_1251:
    case ENC_CP_1253:
    case ENC_CP_1254:
    case ENC_CP_1255:
    case ENC_CP_1256:
    case ENC_CP_1257:
    case ENC_CP_1258:
    case ENC_ISO_8859_1:
    case ENC_ISO_8859_2:
    case ENC_ISO_8859_3:
    case ENC_ISO_8859_4:
    case ENC_ISO_8859_5:
    case ENC_ISO_8859_6:
    case ENC_ISO_8859_7:
    case ENC_ISO_8859_8:
    case ENC_ISO_8859_9:
    case ENC_ISO_8859_10:
    case ENC_ISO_8859_11:
    case ENC_ISO_8859_13:
    case ENC_ISO_8859_14:
    case ENC_ISO_8859_15:
    case ENC_ISO_8859_16:
        return true;
    default:
        return false;
    }
}


}} // namespace jag::pdf

/** EOF @file */
