// Copyright (c) 2005-2009 Jaroslav Gresula
//
// Distributed under the MIT license (See accompanying file
// LICENSE.txt or copy at http://jagpdf.org/LICENSE.txt)
//


#include "precompiled.h"

// this is is a orphan file that has been generated by genexc.py but
// now waits for a new implementation of logging system

#include <interfaces/message_severity.h>
#include <core/errlib/msgcodes.h>

namespace jag
{

const MessageRecord msg_records[TOTAL_NUMBER_OF_MESSAGES]=
{
    { "Font copyright does not allow embedding (font '%s').", 10001, MSG_WARNING },        //WRN_TT_EMBEDDING_NOT_ALLOWED_w
    { "Embedding of Type1 fonts is not supported (font '%s').", 10002, MSG_WARNING },        //WRN_TYPE1_EMBEDDING_NOT_SUPPORTED_w
    { "PNG format warning: %s.", 10201, MSG_WARNING },        //WRN_WARNING_WHILE_PROCESSING_PNG_FORMAT_w
    { "Unknown resolution of PNG image, setting to %d dpi.", 10202, MSG_WARNING },        //WRN_UNKOWN_PNG_RESOLUTION_i
    { "Image has more than one color key mask. Using only the first one.", 10204, MSG_WARNING },        //WRN_PNG_MORE_THEN_ONE_COLOR_KEY_MASK
    { "Alpha channel ignored as this feature is supported from PDF version 1.4.", 10205, MSG_WARNING },        //WRN_ALPHA_IGNORED
    { "Image mask is ignored as it is supported from version 1.3.", 10206, MSG_WARNING },        //WRN_IMAGE_MASK_IGNORED
    { "Color key mask is ignored as it is supported from version 1.3.", 10207, MSG_WARNING },        //WRN_COLOR_KEY_MASK_IGNORED
    { "An alternate image for printing is ignored as it is supported from version 1.3.", 10208, MSG_WARNING },        //WRN_ALTERNATE_FOR_PRINTING_IGNORED
    { "Image rendering intent specified in configuration is out of range. Using RelativeColorimetric.", 10209, MSG_WARNING },        //WRN_IMAGE_RENDERING_INTENT_OUT_OF_RANGE
    { "Path painting operator invoked but no path object is opened.", 10210, MSG_WARNING },        //WRN_PAINTING_NOTHING
    { "Graphics state was modified during path construction but that modification had no effect on the painted path.", 10211, MSG_WARNING },        //WRN_GR_STATE_MODIFIED_WITHIN_PATH_CONSTRUCTION
    { "FreeType finalization failed with code %d.", 10212, MSG_WARNING },        //WRN_FREETYPE_FINALIZATION_FAILED_i
    { "Document not created as no pages were defined.", 10213, MSG_WARNING },        //WRN_EMPTY_DOCUMENT
    { "No current font set.", 10214, MSG_WARNING },        //WRN_NO_FONT_SENT
    { "Glyph index %u to font %s is out of range. Max index is 65535 (0xffff). 0 is used instead.", 10215, MSG_WARNING },        //WRN_GLYPH_INDEX_OUT_OF_RANGE_uw
    { "Codepoint %u not found in font %s.", 10216, MSG_WARNING },        //WRN_CODEPOINT_NOT_FOUND_IN_FONT_uw
    { "Fallback font is used instead of '%s'.", 10217, MSG_WARNING },        //WRN_FALLBACK_FONT_USED_INSTEAD_w
    { "Forced to embed font %s regardless of its copyright information.", 10218, MSG_WARNING },        //WRN_FORCED_EMBEDDING_w
    { "Soft mask uses matte, but its dimensions differ from the parent image.", 10219, MSG_WARNING },        //WRN_MATTE_DIMENSIONS_MISMATCH
    { "Testovaci message.", 20000, MSG_INFO },        //INF_TEST_MESSAGE
    { "Testovaci message with '%s'.", 20001, MSG_INFO },        //INF_TEST_MESSAGE_w
};

} //namespace jag
